name: netflix_api
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0-190.1.beta <4.0.0"

dependencies:
  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  palette_generator: ^0.3.3+3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
